### ISSUE TITLE
silent parameter in options or in call to MARSS?

### ISSUE THREAD

**Issue by joacorapela** [nwfsc-timeseries/MARSS#113]
Hello,

When calling MARSS, if I use the silent parameter in the options list I get:

Error: 
Stopped in checkMARSSInputs(): elements silent is not allowed in arg control (misspelled?).

I put silent as a parameter in the call to MARSS and it worked well.

I checked the documentation and the silent parameter appears both in the options list and in the call to MARSS. 

I am running MARSS  ‘3.11.1’ from CRAN.

Maybe the documentation needs to be updated to indicate that the silent parameter should be only in the call to MARSS?

Thanks for this great package!

J.

**Comment by eeholmes** [comment]
Thanks! Fixed. --Eli
