### ISSUE TITLE
MARSS for trial data?

### ISSUE THREAD

**Issue by joacorapela** [nwfsc-timeseries/MARSS#114]
I want to apply MARSS to trial data. Differently from a long contiguous multivariate time series, trial data consists of a number of shorter independent multivariate time series. For example, trial data could consist of 100 trials and each independent trial could be 20 seconds long.

I would like to estimate parameters of a MARSS model using trial data. Most parameters should be shared across trials, and I want to use data from all trials to constrain these parameters. But each trial should have its own initial state mean and covariance.                                                          

Is there a way to use MARSS to fit models to trial data?

Thanks, Joaquin

**Comment by eeholmes** [comment]
Yes this what MARSS is designed to do. Here is a quick example. See the User Guide for many more complex examples.

```
r <- 0.2
q <- 0.1
n <- 30
TT <- 20
dat <- mvtnorm::rmvnorm(TT, mean=rep(0, n), sigma=diag(q,n))
dat <- apply(dat, 2, cumsum)
dat <- t(dat)
dat <- dat + t(mvtnorm::rmvnorm(TT, mean=rep(0, n), sigma=diag(r,n)))

# estimate individual x0
fit <- MARSS(dat, model=list(Q="diagonal and equal", R="diagonal and equal", U="zero"))

# diffuse prior on x0
mod.list <- list(Q="diagonal and equal", R="diagonal and equal", U="zero",x0=matrix(0,n,1), V0=diag(10,n), tinitx=1)
fit <- MARSS(dat, model=mod.list)
```
