### ISSUE TITLE
Default model not working?

### ISSUE THREAD

**Issue by AthenaOgden** [nwfsc-timeseries/MARSS#16]
Using the list of model defaults from p.34 of the MARSS-package documentation:
```
mod1 = list(Z="identity", A="scaling", R="diagonal and equal", B="identity", U="unconstrained",
Q="diagonal and unequal", x0="unconstrained", V0="zero", C="zero",D="zero",c=matrix(0,0,1),
d=matrix(0,0,1), tinitx=0, diffuse=FALSE)

```

d.plank.dat is from 14.4.1 in the log user guide Holmes et al. 2018.

`fit2 <- MARSS(d.plank.dat,model=mod1)    `
  
Outputs:
Error in array(unlist(f), dim = c(dim.f1, 1, Tmax)) : 
  'data' must be of a vector type, was 'NULL'

Shouldn't using the defaults in this way work?

**Comment by eeholmes** [comment]
The default c and d are not matrix(0,0,1) but rather matrix(0,1,1).

From page 33, defaults are
c="zero" and d="zero" no inputs.

It is not stated, but c="zero" is matrix(0,1,1).  If you run
fit2=MARSS(d.plank.dat)
fit2$model
you will see the default model that was selected.

https://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf
