### ISSUE TITLE
Incorrect Error Message

### ISSUE THREAD

**Issue by jntrcs** [nwfsc-timeseries/MARSS#6]
Running a certain model the error message says:

>  For method=kem (EM), if an element of the diagonal of R is 0, the corresponding row of A must be fixed.

However if you run the same model with fit=FALSE and look at the summary, it indicates A as fixed. These two are contradictory.

> marssMLE object $par element is NULL.  Parameters have not been estimated.

> Model form is marxss. Model Structure is
> m: 3 state process(es) named X.DemShare X.calibration X.MSE
> n: 3 observation time series named DemShare calibration MSE
> 
> Z :  design matrix with rows: X.DemShare X.calibration X.MSE (3 x 3) 
> A :  **fixed** and zero (3 x 1) 
> R :  fixed and zero (3 x 3) 
> B :  unconstrained (3 x 3) 
> U :  fixed and zero (3 x 1) 
> Q :  diagonal and unequal (3 x 3) 
> x0 :  fixed and zero (3 x 1) 
> V0 :  identity (3 x 3) 
> D :  unconstrained (3 x 5) 
> C :  fixed and zero (3 x 1) 
> d :  time-varying (5 x 1) 
> c :  fixed and zero (1 x 1) 
> G :  identity (3 x 3) 
> H :  identity (3 x 3) 
> L :  identity (3 x 3)

**Comment by eeholmes** [comment]
Yes, that is a bug.  The check for A fixed is happening before A gets fixed once it is determined that Z is an identity matrix.  When the latter happens, A becomes fixed and 0 if A="scaling" (default).

To get around this, pass in A=matrix(0, 3, 1) to fix A preemptively.

**Comment by eeholmes** [comment]
Problem is different. Test is on the A matrix in marss form. The model has a d input, which will appear as a time-varying A in marss form.

**Comment by eeholmes** [comment]
Fixed by adding more info to the error message and by adding new error to MARSSinfo().
* when par.test = A the message says rows of both A and D need to be fixed.
* added "AZR0" error info to MARSSinfo()
